default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: jcottobboni
  password: "abissal"
  host: localhost

development:
  <<: *default
  database: issue_tracker

test:
  <<: *default
  database: issue_tracker

production:
  <<: *default
  database: issue_tracker
